"""Regression test: the published OpenAPI spec must match the live app.

P0.2 / P3 fix: ``docs/api/openapi.yaml`` is generated by
``scripts/generate_openapi.py`` from the running FastAPI app. If a route
is added or changed and the spec is not regenerated, this test fails.

Two failure modes caught:
1. **Schema drift** — the hand-written (or stale generated) YAML diverges
   from the actual app routes.
2. **Wrong paths** — e.g. an endpoint declared at ``/memories`` instead
   of ``/v1/memories``, or ``/metrics`` instead of ``/v1/metrics``.

This is the source-of-truth test for the OpenAPI contract.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = REPO_ROOT / "docs" / "api" / "openapi.yaml"


@pytest.fixture(scope="module")
def live_spec():
    """Build the FastAPI app and return its generated OpenAPI dict."""
    sys.path.insert(0, str(REPO_ROOT))
    from emerald.api.app import create_app

    return create_app().openapi()


def _load_published_spec() -> dict:
    return yaml.safe_load(SPEC_PATH.read_text())


# ---------- The drift check ----------

def test_published_spec_matches_live_app(live_spec):
    """docs/api/openapi.yaml must reflect the current app's openapi() output.

    Regenerate with: python scripts/generate_openapi.py
    """
    published = _load_published_spec()

    # Compare canonical structure: paths + per-path operation methods.
    live_paths = {p: sorted(m for m in ops if m in {"get", "post", "put", "delete", "patch"})
                  for p, ops in live_spec["paths"].items()
                  if p not in ("/v1/metrics", "/v2/metrics")}
    pub_paths = {p: sorted(m for m in ops if m in {"get", "post", "put", "delete", "patch"})
                 for p, ops in published["paths"].items()
                 if p not in ("/v1/metrics", "/v2/metrics")}

    missing_from_pub = {p: m for p, m in live_paths.items()
                        if sorted(pub_paths.get(p, [])) != m}
    extra_in_pub = {p: m for p, m in pub_paths.items() if p not in live_paths}

    assert not missing_from_pub, (
        f"Routes present in the app but missing or wrong in the published spec: "
        f"{missing_from_pub}. Run `python scripts/generate_openapi.py`."
    )
    assert not extra_in_pub, (
        f"Routes in the published spec but no longer in the app: {extra_in_pub}."
    )


def test_published_spec_paths_have_version_prefix(live_spec):
    """All non-system paths must start with /v1/ or /v2/.

    Catches the bug where paths were declared without the version prefix
    (e.g. ``/memories`` instead of ``/v1/memories``).
    """
    published = _load_published_spec()
    bad = [p for p in published["paths"]
           if not p.startswith("/v1/") and not p.startswith("/v2/")]
    assert not bad, f"Paths without /v1/ or /v2/ prefix: {bad}"


def test_published_spec_does_not_declare_metrics(live_spec):
    """The Prometheus /metrics endpoint must NOT appear in the public spec.

    It is excluded from the auto-generated schema (``include_in_schema=False``)
    and is an infrastructure endpoint, not part of the public API contract.
    The hand-written spec used to declare ``/metrics`` which was both wrong
    (path) and inappropriate (infrastructure in public contract).
    """
    published = _load_published_spec()
    metrics_paths = [p for p in published["paths"] if p.endswith("/metrics")]
    assert not metrics_paths, f"/metrics should not be in public spec: {metrics_paths}"


def test_published_spec_has_security_scheme(live_spec):
    """The public spec must declare the ApiKeyAuth security scheme."""
    published = _load_published_spec()
    schemes = published.get("components", {}).get("securitySchemes", {})
    assert "ApiKeyAuth" in schemes, "Missing ApiKeyAuth security scheme"
    assert schemes["ApiKeyAuth"]["type"] == "http"
    assert schemes["ApiKeyAuth"]["scheme"] == "bearer"


def test_generate_script_runs_clean():
    """The generator script must run end-to-end without error."""
    result = subprocess.run(
        [sys.executable, "scripts/generate_openapi.py", "--check"],
        capture_output=True, text=True, cwd=REPO_ROOT,
    )
    assert result.returncode == 0, (
        f"scripts/generate_openapi.py --check failed:\n"
        f"STDOUT: {result.stdout}\nSTDERR: {result.stderr}"
    )
